paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Products"
        "500":
          description: Error interno del servidor usualmente generado por una query defectuosa o un fallo de conexión con la base de datos
    post:
      summary: Crea un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
           application/json:
            schema:
              $ref: "#/components/requestBodies/bodyProducts"
      responses:
        "200":
          description: El producto se agrego correctamante
        "400":
          description: El producto no se pudo agregar correctamente
        "500":
          description: Error del servidor

  /api/products/{pid}:
    get:
      summary: Obtiene un producto por el id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: id del producto a obtener.
          schema:
            type: string
      responses:
        "200":
          description: El producto fue obtenido satifactoriamente
        "400":
          description: Producto no encontrado
        "500":
          description: Error de servidor
    put:
      summary: Actualizar un producto por el id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: id del producto a actualizar
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/bodyProducts"
      responses:
        "200":
          description: El producto se actualizo satisfactoriamente
        "400":
          description: Producto no encontrado
        "500":
          description:  Error del Servidor
    delete:
      summary: Eliminar un producto por el id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: id del producto a eliminar
          required: true
          schema:
            $type: string
      responses:
        "200":
          description: El producto se elimino correctamente
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Products"
        "400":
          description: Producto no encontrado 
        "500":
          description: Error del servidor

          
components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: string
          description: id autogenerado de mongo
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        code:
          type: string
          description: codigo unico del producto
        price:
          type: number
          description: Precio del producto
        category:
          type: string
          description: Categoria del producto
        stock:
          type: number
          description: stock del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        owner:
          type: string
          description: Rol del usuario que creo el producto
      example:
        _id: ObjectId("65f5b2cd6c6565fafde0338a")
        title: producto ejemplo
        description: descripcion del producto
        code: AB250
        price: 100
        category: mujer
        stock: 20
        thumbnail: sinimg
        owner: admin

  requestBodies:
    bodyProducts:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        code:
          type: string
          description: codigo unico del producto
        price:
          type: number
          description: Precio del producto
        category:
          type: string
          description: Categoria del producto
        stock:
          type: number
          description: stock del producto
        thumbnails:
          type: string
          description: URL de la imagen del producto
        owner:
          type: string
          description: Rol del usuario que creo el producto
      example:
        title: producto ejemplo
        description: descripcion del producto
        code: AB250
        price: 100
        category: mujer
        stock: 20
        thumbnail: sinimg
        owner: admin